# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 17:19
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('brand_food', 'brand_food'), ('salad', 'salad'), ('cold_sneck', 'cold_sneck')], max_length=5), default=None, size=40),
        ),
    ]
