# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 22:03
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170217_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('фірмові_страви', 'фірмові_страви'), ('салат', 'салат'), ('холодна_закуска', 'холодна_закуска'), ('гаряча_закуска', 'гаряча_закуска'), ('перші_страви', 'перші_страви'), ('другі_страви', 'другі_страви'), ('гарнір', 'гарнір'), ('чай', 'чай'), ('кава', 'кава')], max_length=150), default=None, size=40),
        ),
    ]
