# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 11:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 26, 14, 44, 46, 573761)),
        ),
    ]
