# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 11:54
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170326_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('weight', models.IntegerField()),
                ('price', models.IntegerField()),
                ('type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('фірмові_страви', 'фірмові_страви'), ('салат', 'салат'), ('холодна_закуска', 'холодна_закуска'), ('гаряча_закуска', 'гаряча_закуска'), ('перші_страви', 'перші_страви'), ('другі_страви', 'другі_страви'), ('гарнір', 'гарнір'), ('чай', 'чай'), ('кава', 'кава')], max_length=150), default=None, size=40)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 26, 14, 54, 5, 923754)),
        ),
    ]
