# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 16:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170327_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 27, 19, 30, 38, 412954)),
        ),
    ]
