# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 17:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170327_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 27, 20, 54, 56, 40233)),
        ),
    ]
