# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 22:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170328_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 29, 1, 14, 42, 293619)),
        ),
    ]
