# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 22:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170329_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 29, 1, 27, 32, 873693)),
        ),
    ]
