# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 22:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20170329_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 29, 1, 31, 39, 49774)),
        ),
    ]
