# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 18:33
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20170329_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('фірмові_страви', 'фірмові_страви'), ('салат', 'салат'), ('холодна_закуска', 'холодна_закуска'), ('гаряча_закуска', 'гаряча_закуска'), ('перші_страви', 'перші_страви'), ('другі_страви', 'другі_страви'), ('гарнір', 'гарнір'), ('чай', 'чай'), ('кава', 'кава')], max_length=10000), default=None, size=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 1, 21, 33, 31, 15935)),
        ),
    ]
