# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 12:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20170412_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 20, 15, 54, 37, 451389)),
        ),
    ]
