# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 14:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20170420_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 20, 17, 3, 59, 406570)),
        ),
    ]
