# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='image/images.jpg', null=True, upload_to='image/'),
        ),
    ]
