# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='image/images.jpg', null=True, upload_to='media/image/'),
        ),
    ]
