# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20170327_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='image/images.jpg', null=True, upload_to='image/'),
        ),
    ]
