# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20170328_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('img', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
    ]
