# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20170329_0114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News1',
            new_name='Novosti',
        ),
    ]
