# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_novosti'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novosti',
            old_name='content',
            new_name='content1',
        ),
        migrations.RenameField(
            model_name='novosti',
            old_name='img',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='novosti',
            old_name='title',
            new_name='title1',
        ),
    ]
