# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20170329_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='media/image/images.jpg', null=True, upload_to='image/'),
        ),
    ]
