# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_auto_20170401_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='novosti',
            name='content1',
            field=models.CharField(max_length=100000),
        ),
    ]
