# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='type_photo',
            field=models.CharField(choices=[('салатове', 'салатове'), ('марсала', 'марсала'), ('рустік', 'рустік'), ('бірьозове', 'бірьозове')], default='салатове', max_length=30),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='media/image/images.jpg', null=True, upload_to='/image'),
        ),
    ]
