# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_auto_20170412_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('author_name', models.TextField(default='Анонім', max_length=100)),
            ],
        ),
    ]
