# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='image',
        ),
    ]
